modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"
issueTrackerURL="https://github.com/LevelsFR/OS-Cobblemon-Library/issues"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="https://github.com/LevelsFR/OS-Cobblemon-Library"
authors="LevelsFR"
logoFile="assets/os_cobblemon_library/icon.png"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neoforge_min_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="cobblemon"
type="required"
versionRange="[${cobblemon_min_version},${cobblemon_max_version})"
ordering="AFTER"
side="BOTH"
